sonar.projectKey=felipefuhr.github.io
sonar.organization=felipefuhr
sonar.sources=cmd,internal,scripts
sonar.exclusions=**/__pycache__/**,**/*.sarif,dist/**,data/**,templates/**,assets/**,static/**
sonar.go.coverage.reportPaths=coverage.out
