name: Code Quality (SonarCloud)
on:
  push: { branches: [main] }
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: { contents: read }
jobs:
  sonar:
    permissions: { contents: read }
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-sonarcloud.yml@df9c480572ce848d6b704dad8ac9a95b09e585ca # v1.7.1
    with: { working-directory: "." }
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
